### ISSUE TITLE
can't spawn or summon wolf

### ISSUE THREAD

**Issue by JRDagley1** [MrCrayfish/ImprovedWolves#3]
when i use the spawn egg nothing happens and when i try to summon a wolf it says unable to summon entity but i can summon everything else even other mods,please help.

**Comment by MilkissWhite** [comment]
I have same issue. using "wolf spawn egg" and command "/summon" both can not spawn wolf. 

MC 1.15.2
Forge 31.1.14
ImprovedWolves 1.0.0

**Comment by MrCrayfish** [comment]
Do you have any additional mods installed? I tested this myself and it's working fine.

**Comment by MrCrayfish** [comment]
Can you send me your game log? Often when an entity fails to spawn, it will print an error.

**Comment by JRDagley1** [comment]
Yes I have other mods installed. I have the new goblin trader it let’s me summon him just fine.

**Comment by JRDagley1** [comment]
Yes I can but I just don’t know how to get to game log please help

**Comment by MrKacafirekCZ** [comment]
I have the exact same issue.
Forge: 31.1.0
Mods I've installed:
- ImprovedWolves: 1.0.0
[Latest.zip](https://github.com/MrCrayfish/ImprovedWolves/files/4250206/Latest.zip)

**Comment by Anjoellp** [comment]
I had the same issue.
here is the exception:
java.lang.IllegalArgumentException: Duplicate id value for 17!
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:83) ~[?:?]
	at net.minecraft.entity.passive.WolfEntity.func_70088_a(WolfEntity.java:122) ~[?:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:218) ~[?:?]
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:198) ~[?:?]
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:99) ~[?:?]
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?]
	at net.minecraft.entity.AgeableEntity.<init>(SourceFile:32) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.<init>(SourceFile:31) ~[?:?]
	at net.minecraft.entity.passive.TameableEntity.<init>(SourceFile:32) ~[?:?]
	at net.minecraft.entity.passive.WolfEntity.<init>(WolfEntity.java:73) ~[?:?]
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:418) ~[?:?]
	at net.minecraft.entity.EntityType.func_220349_b(EntityType.java:308) ~[?:?]
	at net.minecraft.entity.EntityType.func_220342_a(EntityType.java:300) ~[?:?]
	at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:295) ~[?:?]
	at net.minecraft.item.SpawnEggItem.func_195939_a(SourceFile:82) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:609) ~[?:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:167) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:344) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:639) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by shaun-wallace** [comment]
I am running 1.15.2-forge-31.2.0 and I have the same issue. 

My error in the log file is the same as above (duplicate id for value 17) and the only mods are all the 1.15.2 MrCrayfish Mods and the gravestone mod:
backpacked-1.4.1-mc1.15.2.jar
enchantable-1.3.0-mc1.15.2.jar
furniture-7.0.0-pre16-1.15.1.jar
glasscutter-1.0.1-mc1.15.2.jar
goblintraders-1.2.0-mc1.15.2.jar
goldenhopper-1.1.1-mc1.15.2.jar
gravestone-1.17.5.jar
improvedwolves-1.1.1-mc1.15.2.jar
obfuscate-0.4.3-1.15.2.jar
vehicle-0.44.0-mc1.15.2.jar
venture-1.0.0-mc1.15.2.jar

Maybe the problem lies here:
[20Jun2020 09:35:47.446] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager/]: defineId called for: class net.minecraft.entity.passive.WolfEntity from class com.mrcrayfish.improvedwolves.common.CustomDataParameters
[20Jun2020 09:35:47.447] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager/]: defineId called for: class net.minecraft.entity.player.PlayerEntity from class com.mrcrayfish.improvedwolves.common.CustomDataParameters


Here is an extract of the log file, I have selected a few of the errors from the file and not just the wolf error in case it helps you find the issue.

[20Jun2020 09:35:41.585] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe cfm:craft_sofa
com.google.gson.JsonSyntaxException: Invalid vehicle entity: vehicle:sofa
	at com.mrcrayfish.vehicle.crafting.VehicleRecipeSerializer.read(VehicleRecipeSerializer.java:48) ~[?:0.44.0-1.15.2]
	at com.mrcrayfish.vehicle.crafting.VehicleRecipeSerializer.func_199425_a_(VehicleRecipeSerializer.java:23) ~[?:0.44.0-1.15.2]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$2971/61277557.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$3143/962681568.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[20Jun2020 09:35:41.587] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe vehicle:steep_boost_ramp
com.google.gson.JsonSyntaxException: Unknown item 'vehicle:boost_pad'
	at net.minecraft.item.crafting.Ingredient.lambda$deserializeItemList$12(Ingredient.java:214) ~[?:?]
	at net.minecraft.item.crafting.Ingredient$$Lambda$4147/1790155126.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:213) ~[?:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:187) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe.func_192408_a(ShapedRecipe.java:254) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe.access$000(ShapedRecipe.java:24) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:278) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$2971/61277557.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$3143/962681568.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[20Jun2020 09:35:41.599] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe vehicle:boost_ramp
com.google.gson.JsonSyntaxException: Unknown item 'vehicle:boost_pad'
	at net.minecraft.item.crafting.Ingredient.lambda$deserializeItemList$12(Ingredient.java:214) ~[?:?]
	at net.minecraft.item.crafting.Ingredient$$Lambda$4147/1790155126.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:213) ~[?:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:187) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe.func_192408_a(ShapedRecipe.java:254) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe.access$000(ShapedRecipe.java:24) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:278) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$2971/61277557.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$3143/962681568.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[20Jun2020 09:35:41.623] [Server thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe vehicle:boost_pad
com.google.gson.JsonSyntaxException: Unknown item 'vehicle:boost_pad'
	at net.minecraft.item.crafting.ShapedRecipe.lambda$deserializeItem$0(ShapedRecipe.java:264) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$$Lambda$4148/289292171.get(Unknown Source) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_51]
	at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:263) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:283) ~[?:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:274) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:134) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:60) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:37) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$2971/61277557.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$3143/962681568.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:77) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

[20Jun2020 10:18:08.745] [Render thread/ERROR] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Received invalid update packet for null tile entity at BlockPos{x=698, y=63, z=699} with data: {Vehicle:"vehicle:off_roader",WheelType:0,Opened:1b,EngineTier:0,OpenerLeast:-8573329198489681773L,Color:16383998,x:698,OpenerMost:-9009810480796778462L,y:63,z:699,id:"vehicle:vehicle_crate"}

[20Jun2020 15:50:53.963] [Server thread/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Sending ticking packet info 'com.mrcrayfish.obfuscate.network.HandshakeMessages$S2CSyncedPlayerData' to 'obfuscate:handshake' sequence 4
[20Jun2020 15:50:53.963] [Netty Local Client IO #1/DEBUG] [net.minecraftforge.fml.network.FMLLoginWrapper/FMLHANDSHAKE]: Recieved login wrapper packet event for channel obfuscate:handshake with index 4
[20Jun2020 15:50:53.963] [Netty Local Client IO #1/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Received client indexed reply 4 of type com.mrcrayfish.obfuscate.network.HandshakeMessages$S2CSyncedPlayerData
[20Jun2020 15:50:53.963] [Netty Local Client IO #1/ERROR] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Recieved unexpected index 4 in client reply
[20Jun2020 15:50:53.964] [Netty Local Client IO #1/DEBUG] [Obfuscate/OBFUSCATE_HANDSHAKE]: Received synced key mappings from server
[20Jun2020 15:50:53.964] [Netty Local Client IO #1/DEBUG] [net.minecraftforge.fml.network.FMLLoginWrapper/FMLHANDSHAKE]: Dispatching wrapped packet reply for channel obfuscate:handshake with index 4
[20Jun2020 15:50:53.964] [Netty Server IO #3/DEBUG] [net.minecraftforge.fml.network.FMLLoginWrapper/FMLHANDSHAKE]: Recieved login wrapper packet event for channel obfuscate:handshake with index 4
[20Jun2020 15:50:53.964] [Netty Server IO #3/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Received client indexed reply 4 of type com.mrcrayfish.obfuscate.network.HandshakeMessages$C2SAcknowledge
[20Jun2020 15:50:53.964] [Netty Server IO #3/DEBUG] [Obfuscate/OBFUSCATE_HANDSHAKE]: Received acknowledgement from client
[20Jun2020 15:50:53.968] [Server thread/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Handshake complete!
[20Jun2020 15:50:53.973] [Netty Local Client IO #1/INFO] [net.minecraftforge.fml.network.NetworkHooks/]: Connected to a modded server.

[20Jun2020 16:06:25.429] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Unable to summon entity
[20Jun2020 16:06:43.221] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IllegalArgumentException: Duplicate id value for 17!
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:83) ~[?:?]
	at net.minecraft.entity.passive.WolfEntity.func_70088_a(WolfEntity.java:122) ~[?:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:218) ~[?:?]
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:198) ~[?:?]
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:99) ~[?:?]
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?]
	at net.minecraft.entity.AgeableEntity.<init>(SourceFile:32) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.<init>(SourceFile:31) ~[?:?]
	at net.minecraft.entity.passive.TameableEntity.<init>(SourceFile:32) ~[?:?]
	at net.minecraft.entity.passive.WolfEntity.<init>(WolfEntity.java:73) ~[?:?]
	at net.minecraft.entity.EntityType$$Lambda$1308/1416225284.create(Unknown Source) ~[?:?]
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:418) ~[?:?]
	at net.minecraft.entity.EntityType.func_220349_b(EntityType.java:308) ~[?:?]
	at net.minecraft.entity.EntityType.func_220342_a(EntityType.java:300) ~[?:?]
	at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:295) ~[?:?]
	at net.minecraft.item.SpawnEggItem.func_195939_a(SourceFile:82) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:610) ~[?:?]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:167) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:344) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$4955/2006713331.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

Hope that helps.
